<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="kundeRegistrering._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="jumbotron">
        <h1 style="float: left">Paradise Hotel</h1>
        
        <div style="float: right">
            <p>Søk etter din reservasjon</p>
             <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
            <br/>
            <asp:Button ID="Button2" runat="server" Text="Søk" OnClick="Button2_Click" />
            <p>
            <asp:GridView ID="GridView1" AutoGenerateDeleteButton="true"  runat="server" AutoGenerateColumns="False" DataKeyNames="ID" DataSourceID="SqlDataSource2">
              
                 <Columns>
                    
                    <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                    <asp:BoundField DataField="Navn" HeaderText="Navn" SortExpression="Navn" />
                    <asp:BoundField DataField="AntallDager" HeaderText="AntallDager" SortExpression="AntallDager" />
                    <asp:BoundField DataField="Startdato" HeaderText="Startdato" SortExpression="Startdato" />
                </Columns>

               
            </asp:GridView>

            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:guestConnectionString %>" ProviderName="<%$ ConnectionStrings:guestConnectionString.ProviderName %>" SelectCommand="SELECT ID, Navn, AntallDager, Startdato FROM hotelguest WHERE (ID = ?)" DeleteCommand="DELETE FROM hotelguest WHERE (ID = ?)">
                <SelectParameters>
                    <asp:ControlParameter ControlID="TextBox4" Name="ID" PropertyName="Text" Type="Int32" />
                </SelectParameters>
            </asp:SqlDataSource>
            </p>
        </div>
        <div style="float: left;">
        <p>
            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
&nbsp;Navn
        </p>
        <p>
            <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
&nbsp;StartDato</p>
        <p>
            <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
&nbsp;Antall dager</p>
        <p>
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Reserver" />
        </p>
        </div>
        <div style="clear: both"></div>
    </div>

   

</asp:Content>
